config/routes.rb
Rails.application.routes.draw do
  get 'question', to: 'questions#ask'
  get 'answer', to: 'questions#answer'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/coaches_controller.rb
class CoachesController < ApplicationController
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  QUESTIONS = ['I am going to work', '?', '']
  ANSWERS = ['Great!', 'Silly question, get dressed and go to work!', "I don't care, get dressed and go to work!"]

  def ask
    # @ask = params['ask']
  end

  def answer
    @answer = params['ask']
    if @answer == QUESTIONS[0]
      @coach = ANSWERS[0]
    elsif @answer == QUESTIONS[1]
      @coach = ANSWERS[1]
    else
      @coach = ANSWERS[2]
    end
    # @answer = ANSWERS.select { |answer|  answer[]}
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coaches_helper.rb
module CoachesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsStupidCoaching</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/answer.html.erb
<h1>Stupid Coaching</h1>
<p>Find me in app/views/questions/answer.html.erb</p>


<div class="questions">
  <blockquote><%= @answer  %></blockquote>
</div>

<div class="answers">
  <blockquote><%= @coach %>
    <%= simple_format("- Your coach")  %></blockquote></div>

<%= link_to "Ask a new queston", question_path %>

app/views/questions/ask.html.erb
<h1>Questions#ask</h1>
<p>Find me in app/views/questions/ask.html.erb</p>

<form action="answer">
  <input type="text" name="ask">
  <input type="submit" value="Ask!">
</form>